# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setmoduleoftraction.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setModuleOfTraction(object):
    def setupUi(self, setModuleOfTraction):
        setModuleOfTraction.setObjectName("setModuleOfTraction")
        setModuleOfTraction.resize(375, 398)
        setModuleOfTraction.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridLayout = QtWidgets.QGridLayout(setModuleOfTraction)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_module_final_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_module_final_2.setObjectName("lineEdit_module_final_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_module_final_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_angle_final_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_angle_final_2.setObjectName("lineEdit_angle_final_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_angle_final_2)
        self.checkBox_perp_final_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_perp_final_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_perp_final_2.setObjectName("checkBox_perp_final_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_perp_final_2)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_module_middle = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_module_middle.setObjectName("lineEdit_module_middle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_module_middle)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_angle_middle = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_angle_middle.setObjectName("lineEdit_angle_middle")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_angle_middle)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(setModuleOfTraction)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_module_initial = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_module_initial.setObjectName("lineEdit_module_initial")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_module_initial)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_angle_initial = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_angle_initial.setObjectName("lineEdit_angle_initial")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_angle_initial)
        self.checkBox_apply_same_all = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_apply_same_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_apply_same_all.setObjectName("checkBox_apply_same_all")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_apply_same_all)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 2)

        self.retranslateUi(setModuleOfTraction)
        self.buttonBox.accepted.connect(setModuleOfTraction.accept)
        self.buttonBox.rejected.connect(setModuleOfTraction.reject)
        # self.lineEdit_module_initial.textChanged['QString'].connect(self.lineEdit_module_middle.setText)
        self.lineEdit_module_initial.textChanged['QString'].connect(lambda: self.setTextOneCondition(self.lineEdit_module_middle, self.groupBox_2.isDisabled()))
        self.lineEdit_angle_initial.textChanged['QString'].connect(self.lineEdit_angle_middle.setText)
        self.checkBox_apply_same_all.toggled['bool'].connect(self.groupBox_2.setDisabled)
        self.checkBox_perp_final_2.toggled['bool'].connect(self.lineEdit_angle_final_2.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(setModuleOfTraction)
        setModuleOfTraction.setTabOrder(self.lineEdit_module_initial, self.lineEdit_angle_initial)
        setModuleOfTraction.setTabOrder(self.lineEdit_angle_initial, self.checkBox_apply_same_all)
        setModuleOfTraction.setTabOrder(self.checkBox_apply_same_all, self.lineEdit_module_middle)
        setModuleOfTraction.setTabOrder(self.lineEdit_module_middle, self.lineEdit_angle_middle)
        setModuleOfTraction.setTabOrder(self.lineEdit_angle_middle, self.lineEdit_module_final_2)
        setModuleOfTraction.setTabOrder(self.lineEdit_module_final_2, self.lineEdit_angle_final_2)
        
    def setTextOnCondition(self, text, lineEdit, condition):
    	if condition:
    		lineEdit.super().setText(text)

    def retranslateUi(self, setModuleOfTraction):
        _translate = QtCore.QCoreApplication.translate
        setModuleOfTraction.setWindowTitle(_translate("setModuleOfTraction", "Add Nodal Forces or Traction to the Element"))
        self.groupBox_4.setTitle(_translate("setModuleOfTraction", "Element"))
        self.label_7.setText(_translate("setModuleOfTraction", "Module of traction (MPa):"))
        self.label_8.setText(_translate("setModuleOfTraction", "Angle (°)"))
        self.checkBox_perp_final_2.setText(_translate("setModuleOfTraction", "Perpendicular"))
        self.groupBox_2.setTitle(_translate("setModuleOfTraction", "Middle Point"))
        self.label_2.setText(_translate("setModuleOfTraction", "Module of traction (kN):"))
        self.label_4.setText(_translate("setModuleOfTraction", "Angle (°)"))
        self.groupBox_3.setTitle(_translate("setModuleOfTraction", "Initial Extremity Point"))
        self.label_5.setText(_translate("setModuleOfTraction", "Module of traction (kN):"))
        self.label_6.setText(_translate("setModuleOfTraction", "Angle (°)"))
        self.checkBox_apply_same_all.setText(_translate("setModuleOfTraction", "Repeat for all others points"))


