# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setmoduleoftraction.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setModuleOfTraction(object):
    def setupUi(self, setModuleOfTraction):
        setModuleOfTraction.setObjectName("setModuleOfTraction")
        setModuleOfTraction.resize(304, 412)
        setModuleOfTraction.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.gridLayout = QtWidgets.QGridLayout(setModuleOfTraction)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_x_element = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_x_element.setObjectName("lineEdit_x_element")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_x_element)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_y_element = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_y_element.setObjectName("lineEdit_y_element")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_y_element)
        self.radioButton_global_coord = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_global_coord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_global_coord.setChecked(True)
        self.radioButton_global_coord.setObjectName("radioButton_global_coord")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_global_coord)
        self.radioButton_local_coord = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_local_coord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_local_coord.setObjectName("radioButton_local_coord")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_local_coord)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_x_middle = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_x_middle.setObjectName("lineEdit_x_middle")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_x_middle)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_y_middle = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_y_middle.setObjectName("lineEdit_y_middle")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_y_middle)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(setModuleOfTraction)
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(setModuleOfTraction)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_x_initial = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_x_initial.setObjectName("lineEdit_x_initial")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_x_initial)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_y_initial = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_y_initial.setObjectName("lineEdit_y_initial")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_y_initial)
        self.checkBox_apply_same_all = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_apply_same_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_apply_same_all.setObjectName("checkBox_apply_same_all")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_apply_same_all)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 2)

        self.retranslateUi(setModuleOfTraction)
        self.buttonBox.accepted.connect(setModuleOfTraction.accept)
        self.buttonBox.rejected.connect(setModuleOfTraction.reject)
        self.lineEdit_x_initial.textChanged['QString'].connect(self.lineEdit_x_middle.setText)
        self.lineEdit_y_initial.textChanged['QString'].connect(self.lineEdit_y_middle.setText)
        self.checkBox_apply_same_all.toggled['bool'].connect(self.groupBox_2.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(setModuleOfTraction)
        setModuleOfTraction.setTabOrder(self.lineEdit_x_initial, self.lineEdit_y_initial)
        setModuleOfTraction.setTabOrder(self.lineEdit_y_initial, self.checkBox_apply_same_all)
        setModuleOfTraction.setTabOrder(self.checkBox_apply_same_all, self.lineEdit_x_middle)
        setModuleOfTraction.setTabOrder(self.lineEdit_x_middle, self.lineEdit_y_middle)
        setModuleOfTraction.setTabOrder(self.lineEdit_y_middle, self.lineEdit_y_element)
        setModuleOfTraction.setTabOrder(self.lineEdit_x_element, self.lineEdit_y_element)
        self.lineEdit_x_initial.setFocus()

    def retranslateUi(self, setModuleOfTraction):
        _translate = QtCore.QCoreApplication.translate
        setModuleOfTraction.setWindowTitle(_translate("setModuleOfTraction", "Add Nodal Forces or Traction to the Element"))
        self.groupBox_4.setTitle(_translate("setModuleOfTraction", "Element"))
        self.label_7.setText(_translate("setModuleOfTraction", "x (MPa):"))
        self.label_8.setText(_translate("setModuleOfTraction", "y (MPa)"))
        self.radioButton_global_coord.setText(_translate("setModuleOfTraction", "Global coordiates"))
        self.radioButton_local_coord.setText(_translate("setModuleOfTraction", "Local coordinates"))
        self.groupBox_2.setTitle(_translate("setModuleOfTraction", "Middle Point"))
        self.label_2.setText(_translate("setModuleOfTraction", "x (kN):"))
        self.label_4.setText(_translate("setModuleOfTraction", "y (kN)"))
        self.groupBox_3.setTitle(_translate("setModuleOfTraction", "Initial Extremity Point"))
        self.label_5.setText(_translate("setModuleOfTraction", "x (kN):"))
        self.label_6.setText(_translate("setModuleOfTraction", "y (kN)"))
        self.checkBox_apply_same_all.setText(_translate("setModuleOfTraction", "Repeat for middle point"))
